[workspace]
authors = ["Padraic Shafer <pshafer@bnl.gov>"]
channels = ["conda-forge"]
name = "example"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
lab = { cmd = "jupyter lab", description = "Launch JupyterLab" }
start = { depends-on = [{ task = "lab" }], description = "Start exploring the Pixi project" }

[dependencies]
python = ">=3.14.0,<3.15"
numpy = ">=2.3.4,<3"
notebook = ">=7.4.7,<8"
jupyterlab = ">=4.4.10,<5"

[feature.dev.dependencies]
pre-commit = ">=4.4.0,<5"

[environments]
dev = ["dev"]

