[workspace]
authors = ["Padraic Shafer <pshafer@bnl.gov>"]
channels = ["conda-forge"]
name = "cuda-exercise"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.cpu.dependencies]
pytorch-cpu = ">=2.8.0,<3"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = ">=2.8.0,<3"

[feature.gpu.target.win-64.dependencies]
pytorch-gpu = ">=2.8.0,<3"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
